fix: prevents creating duplicate user in db by changing db structure and lambda email-confirm method

diff --git a/backend-flask/bin/db-setup b/backend-flask/bin/db-setup
--- a/backend-flask/bin/db-setup
+++ b/backend-flask/bin/db-setup
@@ -1,5 +1,5 @@
 #!/usr/bin/bash
--e #exit on error
+set -e #exit on error
 
 source $(dirname $0)/.env
 
@@ -8,8 +8,6 @@ if [ "$ENV_TYPE" = "prod" ]; then
 else
     printf "\033[1;36m == db-setup localhost-postgresql \033[0m\n " 
 fi
-
-
 
 source "./db-create" #create db
 source "./db-schema-load" #create tables
